server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081
  requestLog:
    appenders: []

logging:
  level: WARN
  loggers:
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: WARN
  appenders:
    - type: console

metrics:
  frequency: 1 hour
  reporters:
    - type: csv

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: std-user
  password: pAssw0rd
  url: jdbc:mysql://192.168.1.112/std_db
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    minSize: 1
    maxSize: 5
    maxWaitForConnection: 1s
    hibernate.show_sql: false

taskTypes:
  - id: "RES"
    className: "pvytykac.net.scrape.server.task.impl.ResTaskType"
  - id: "JUSTICE"
    className: "pvytykac.net.scrape.server.task.impl.JusticeTaskType"
