server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081
  requestLog:
    appenders:
    - type: file
      currentLogFilename: logs/access.log
      archivedLogFilenamePattern: logs/access.%d.log
      archive: true
      archivedFileCount: 7

logging:
  level: WARN
  loggers:
    org.hibernate.SQL:
      level: TRACE
      appenders:
        - type: file
          currentLogFilename: logs/sql.log
          archivedLogFilenamePattern: logs/sql.%d.log.gz
          archivedFileCount: 7
    pvytykac.net:
      level: DEBUG
      appenders:
        - type: file
          currentLogFilename: logs/application.log
          archivedLogFilenamePattern: logs/application.%d.log.gz
          archivedFileCount: 7
  appenders:
  - type: file
    threshold: WARN
    currentLogFilename: logs/error.log
    archivedLogFilenamePattern: logs/error.%d.log.gz
    archivedFileCount: 7

metrics:
  frequency: 1 hour
  reporters:
    - type: csv

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: std-user
  password: pAssw0rd
  url: jdbc:mysql://192.168.1.112/std_db
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    minSize: 1
    maxSize: 5
    maxWaitForConnection: 1s

taskTypes:
  - id: "RES"
    className: "pvytykac.net.scrape.server.task.impl.ResTaskType"
  - id: "JUSTICE"
    className: "pvytykac.net.scrape.server.task.impl.JusticeTaskType"
